Description: >
    Template for creating a single ec2 instance and an attached security group.  Also allows you to specify existing security groups to attach.
Parameters:

    InstanceName:
        Description: The name tag for the instance
        Type: String

    Subnet:
        Description: The subnet in which to deploy the instance
        Type: AWS::EC2::Subnet::Id   

    Contact:
        Description: Contact email
        Default: foo@bar.com
        Type: String    

    InstanceAMI:
        Description: AMI for the instance
        Type: String

    InstanceType:
        Description: what instance type the ec2 instance should use
        Default: t2.nano
        AllowedValues: 
          - t2.nano
          - t2.micro
          - t2.small
        Type: String



Resources:

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile: EC2InstanceProfileForSystemsManager
      SubnetId:
        Ref: Subnet
      Tags:
        - Key: Contact
          Value: !Ref Contact
        - Key: Name
          Value: !Ref InstanceName  


Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyInstance
