---
AWSTemplateFormatVersion: '2010-09-09'
Description: A test stack for demonstrating Cloudformation
Parameters:
  Subnet:
    Description: Subnet in which to place the resources
    Type: AWS::EC2::Subnet::Id
  SecurityGroup:
    Description: This group will be applied to both the ELB and instances in the ASG
    Type: AWS::EC2::SecurityGroup::Id
  KeyName:
    Description: The ssh key you want to use for instances
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: The instance type for the Launch Config
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
Resources:
  MyLoadBalancer: 
    Type: AWS::ElasticLoadBalancing::LoadBalancer   
    Properties:
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP   
      Subnets:
        - Ref: Subnet
      SecurityGroups:
        - Ref: SecurityGroup        
  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration    
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install nginx -y
          sudo service nginx start
      ImageId: ami-6869aa05
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName  
      SecurityGroups:
        - Ref: SecurityGroup
  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LoadBalancerNames:
        - Ref: MyLoadBalancer
      LaunchConfigurationName:
        Ref: MyLaunchConfiguration
      DesiredCapacity: 1
      MinSize: 1        
      MaxSize: 4
      VPCZoneIdentifier:  
        - Ref: Subnet
Outputs:
  LoadBalancerDNSName:
    Description: The DNS name of the ELB
    Value: !GetAtt MyLoadBalancer.DNSName